<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EDM-VM-CL01" failures="1" tests="3" name="tests.ATestRegressionRereference" time="115.808" errors="0" timestamp="2022-09-07T06:18:31 GMT-07:00" skipped="2">
  <testcase classname="tests.ATestRegressionRereference" name="VerifyThatLockedDocumentCanRereference" time="115.808">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at main.EDRM.hybridFramework.helper.assertion.AssertionHelper.verifyTextContains(AssertionHelper.java:37)
at tests.ATestRegressionRereference.VerifyThatLockedDocumentCanRereference(ATestRegressionRereference.java:155)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- VerifyThatLockedDocumentCanRereference -->
  <system-out/>
  <testcase classname="tests.ATestRegressionRereference" name="VerifyErrorMessageWhileReReferenceOfCheckedOutDoc">
    <skipped/>
  </testcase> <!-- VerifyErrorMessageWhileReReferenceOfCheckedOutDoc -->
  <system-out/>
  <testcase classname="tests.ATestRegressionRereference" name="VerifyLockedDocumentStatusInAnotherFSAfterReReference">
    <skipped/>
  </testcase> <!-- VerifyLockedDocumentStatusInAnotherFSAfterReReference -->
  <system-out/>
</testsuite> <!-- tests.ATestRegressionRereference -->
